# Generated by Django 4.2.5 on 2023-10-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата продаж')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('pr_sku_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, verbose_name='Товар')),
                ('pr_group_id', models.CharField(max_length=200, verbose_name='Группа')),
                ('pr_cat_id', models.CharField(max_length=200, verbose_name='Категория')),
                ('pr_subcat_id', models.CharField(max_length=200, verbose_name='Подкатегория')),
                ('pr_uom_id', models.IntegerField(verbose_name='Единицы измерения')),
            ],
            options={
                'ordering': ('pr_sku_id',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('st_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, verbose_name='магазин')),
                ('st_city_id', models.CharField(max_length=200, verbose_name='город')),
                ('st_division_code', models.CharField(max_length=200, verbose_name='дивизион')),
                ('st_type_format_id', models.IntegerField(verbose_name='формат')),
                ('st_type_loc_id', models.IntegerField(verbose_name='тип локации/окружения')),
                ('st_type_size_id', models.IntegerField(verbose_name='размер')),
                ('st_is_active', models.IntegerField(verbose_name='активность')),
            ],
            options={
                'ordering': ('st_id',),
            },
        ),
        migrations.CreateModel(
            name='SalesFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_type', models.IntegerField(verbose_name='тип продаж')),
                ('sales_units', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='всего шт')),
                ('sales_units_promo', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='промо шт')),
                ('sales_rub', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='всего руб')),
                ('sales_run_promo', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='промо руб')),
                ('st_sku_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_store_date', to='products.sales', verbose_name='магазин-товар-дата')),
            ],
            options={
                'ordering': ('st_sku_date',),
            },
        ),
        migrations.CreateModel(
            name='SalesDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_sales_units', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='разница шт')),
                ('wape', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='wape')),
                ('st_sku_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_sales_store_date', to='products.sales', verbose_name='магазин-товар-дата')),
            ],
            options={
                'ordering': ('st_sku_date',),
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='pr_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sku', to='products.sku', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='sales',
            name='st_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_store', to='products.store', verbose_name='магазин'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_units', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='всего шт')),
                ('forecast_date', models.DateField(verbose_name='дата прогноза')),
                ('st_sku_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_sales_store_date', to='products.sales', verbose_name='магазин-товар-дата')),
            ],
            options={
                'ordering': ('-forecast_date',),
            },
        ),
    ]
