# Generated by Django 4.2.5 on 2023-09-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('pr_sku_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, verbose_name='Товар')),
                ('pr_group_id', models.CharField(max_length=200, verbose_name='Группа')),
                ('pr_cat_id', models.CharField(max_length=200, verbose_name='Категория')),
                ('pr_subcat_id', models.CharField(max_length=200, verbose_name='Подкатегория')),
                ('pr_uom_id', models.IntegerField(verbose_name='Единицы измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('st_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, verbose_name='магазин')),
                ('st_city_id', models.CharField(max_length=200, verbose_name='город')),
                ('st_division_code', models.CharField(max_length=200, verbose_name='дивизион')),
                ('st_type_format_id', models.IntegerField(verbose_name='формат')),
                ('st_type_loc_id', models.IntegerField(verbose_name='тип локации/окружения')),
                ('st_type_size_id', models.IntegerField(verbose_name='размер')),
                ('st_is_active', models.IntegerField(verbose_name='активность')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата прогноза')),
                ('sales_type', models.IntegerField(verbose_name='тип продаж')),
                ('sales_units', models.IntegerField(verbose_name='всего шт')),
                ('sales_units_promo', models.IntegerField(verbose_name='промо шт')),
                ('sales_rub', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='всего руб')),
                ('sales_run_promo', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='промо руб')),
                ('pr_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sku', to='products.sku', verbose_name='товар')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_store', to='products.store', verbose_name='магазин')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ForecastSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateTimeField(verbose_name='Дата прогноза')),
                ('pr_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_sku', to='products.sku', verbose_name='товар')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_store', to='products.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'прогноз',
                'verbose_name_plural': 'прогнозы',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата прогноза')),
                ('target', models.IntegerField(verbose_name='цель')),
                ('forecast_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='products.forecastsku')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
