# Generated by Django 4.2.5 on 2023-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_units',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='всего шт'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_units_promo',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='промо шт'),
        ),
    ]
