# Generated by Django 4.2.5 on 2023-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_sales_sales_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_rub',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='всего руб'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_run_promo',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='промо руб'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_units',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='всего шт'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_units_promo',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='промо шт'),
        ),
    ]
