# Generated by Django 4.2.5 on 2023-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_sales_sales_rub_alter_sales_sales_run_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastsku',
            name='forecast_date',
            field=models.DateTimeField(verbose_name='дата прогноза'),
        ),
    ]
