# Generated by Django 4.2.5 on 2023-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_forecastsku_forecast_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.DateField(verbose_name='дата прогноза'),
        ),
        migrations.AlterField(
            model_name='forecastsku',
            name='forecast_date',
            field=models.DateField(verbose_name='дата прогноза'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(verbose_name='дата прогноза'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_rub',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='всего руб'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_run_promo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='промо руб'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_units',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='всего шт'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_units_promo',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='промо шт'),
        ),
    ]
