# Generated by Django 4.2.5 on 2023-09-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_forecast_date_alter_forecastsku_forecast_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цель'),
        ),
    ]
