# Generated by Django 4.2.5 on 2023-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_sales_date_alter_sales_sales_rub_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastsku',
            options={'ordering': ['forecast_date'], 'verbose_name': 'прогноз', 'verbose_name_plural': 'прогнозы'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_units',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='всего шт'),
        ),
    ]
